### ISSUE TITLE
ISR in Pythia8 in madgraph5

### ISSUE THREAD

**Issue by umar0341** [mg5amcnlo/mg5amcnlo#11]
HOW TO TURN ON ISR in Pythia8 in madgraph5

**Comment by oliviermattelaer** [comment]
Hi,

For all pythia8 question, the best is to look at the pythia8 manual.

For your question, I can not actually answer it, since I have no clue of 
1) what kind of collider you are talking about (ee or pp)
2) what kind of ISR your are talking about (QCD, QED, resummed, ....)
3) what kind of precision requested for your process (LO or NLO)
    For LO, the card is following strictly the pythia8 convention so the above manual is the solution.
    At NLO, if it is not in the shower_card.dat, then you need to check if what you ask is compatible with the MC counter-term and if it does then you either  need to run pythia8 by hand (i.e. outside of our framework) or hacking our code (which I personally can not do in this case).

Cheers,

Olivier
