### ISSUE TITLE
coloramps differences in fortran and cpp

### ISSUE THREAD

**Issue by valassi** [mg5amcnlo/mg5amcnlo#114]
Hi @oliviermattelaer this is a followup to https://github.com/madgraph5/madgraph4gpu/pull/873 and related issues.

I hope I will manage to idetify the differences in f77 and cpp.
There is one thing anyway that puzzles me, feel free to close as irrelevant

The f77 version has
```
                if (diag_tuple[4]-diag_tuple[5]) == max_Nc:
                    diag_num = diag_tuple[0] + 1
                    # Add this JAMP number to this diag_num
                    diag_jamp[diag_num] = diag_jamp.setdefault(diag_num, []) + \
                                          [ijamp+1]
                else:
                    self.proc_characteristic['single_color'] = False
```
In the cpp version, those two lines are commentd out. Why?

And then there are other subtle differences I am loking at.
Thanks
Andrea

**Comment by valassi** [comment]
Note: the main issue here is fixed in PR #115

@oliviermattelaer  maybe you can still check that `self.proc_characteristic['single_color'] ` line too before closing? Thanks

**Comment by oliviermattelaer** [comment]
Let me comment on this:

self.proc_characteristic is a set of information generated by the code generator and which is passed to the madevent interface as meta-data information about the process (potential issue/limitation and general information).
Metadata which can be used in various way.

So it does not really make sense to include it in export_cpp since this is (already) handle by the export_v4 part 
(and this is really unique to the madevent exporter).

Cheers,

Olivier

PS: So I guess i can close this one

**Comment by valassi** [comment]
Thanks Olivier!
