### ISSUE TITLE
debug mode in generate_events?

### ISSUE THREAD

**Issue by valassi** [mg5amcnlo/mg5amcnlo#123]
Hi @oliviermattelaer sorry stupid question: is there a way to turn on debugging in bin/generate_events?

I see some debug messages depend on `__debug__`.

But then `__debug__` is explicitly switched off by
```
# Check if optimize mode is (and should be) activated
if __debug__ and (not os.path.exists(pjoin(root_path,'../..', 'bin','create_release.py'))):
    subprocess.call([sys.executable] + ['-O'] + sys.argv)
    sys.exit()
```

And if I comment out those lines I get strange side effects like
```
No module named 'madgraph'
 No hepmc reader since No module named 'madgraph' [lhe_parser.py at line 49]
```

Any suggestion?
Thanks
Andrea

PS Originally I am just trying to debug a totally simple issue that follows, but I find no easy way to print out which path it complains about
```
Command "generate_events -f" interrupted with error:
OSError : Cannot call rmtree on a symbolic link
```

**Comment by oliviermattelaer** [comment]
The normal way to have debug mode is to launch from ./bin/mg5_aMC and then do
launch DIRPATH

(and you need to have a mg5 version coming from github and not a release tarball)

Cheers,

Olivier

On 2 Aug 2024, at 13:23, Andrea Valassi ***@***.***> wrote:



Hi @oliviermattelaer<https://github.com/oliviermattelaer> sorry stupid question: is there a way to turn on debugging in bin/generate_events?

I see some debug messages depend on debug.

But then debug is explicitly switched off by

# Check if optimize mode is (and should be) activated
if __debug__ and (not os.path.exists(pjoin(root_path,'../..', 'bin','create_release.py'))):
    subprocess.call([sys.executable] + ['-O'] + sys.argv)
    sys.exit()


And if I comment out those lines I get strange side effects like

No module named 'madgraph'
 No hepmc reader since No module named 'madgraph' [lhe_parser.py at line 49]


Any suggestion?
Thanks
Andrea

PS Originally I am just trying to debug a totally simple issue that follows, but I find no easy way to print out which path it complains about

Command "generate_events -f" interrupted with error:
OSError : Cannot call rmtree on a symbolic link

**Comment by valassi** [comment]
Thanks Olivier. I wanted to use generate_events (as the experiments do I think) and not launch, but it's ok, I found another way to debug this. Closing.
