### ISSUE TITLE
How to subtract VBF diagrams from total diagrams to get only Annihilation diagrams

### ISSUE THREAD

**Issue by umar0341** [mg5amcnlo/mg5amcnlo#15]
**Hi my process is mu+ mu- > mu+ mu- h2 h2 h2 > b b~
i got 2029 diagrams using Madgraph that include both annihilations as well as VBF diagrams
intermediate particle in my process are h1,h2,h3,z,a
i want to separate VBF and Anihiliation diagrams completely I use the following command to subtract all annihilation diagrams from total diagrams i.e
MG5_aMC>generate mu+ mu- > mu+ mu- h2 h2 $$ z a h1 h2 h3, h2 > b b~ and got 1200 diagrams that are all VBF. but I'm trying many formats to subtract VBF from total diagrams to get only Anihiliations diagrams but I am unable to do it.

kindly help me subtract all VBF from total diagrams to get Anihiliation diagrams.**

**Comment by oliviermattelaer** [comment]
I do not know neither the syntax, you tried, nor your model (and therefore waht makes sense)

Did you try something like
mu+ mu- >  Z | a > mu+ mu- h2 h2 h2 > b b~

Otherwise, we have a FAQ for how to do it when simple syntax are not enough:
https://answers.launchpad.net/mg5amcnlo/+faq/3322

Cheers,

Olivier

On 11 Jul 2022, at 06:30, umar0341 ***@***.******@***.***>> wrote:



Hi my process is mu+ mu- > mu+ mu- h2 h2 h2 > b b~
i got 2029 diagrams using madgraph that include both annihilations as well as VBF diagrams
intermediate particle in my process are h1,h2,h3,z,a
i want to separate VBF and Anihiliation diagrams completely I use the following command to subtract all annihilation diagrams from total diagrams i.e
MG5_aMC>generate mu+ mu- > mu+ mu- h2 h2 $$ z a h1 h2 h3, h2 > b b~ and got 1200 diagrams that are all VBF. but I'm trying many formats to subtract VBF from total diagrams to get only Anihiliations diagrams but I am unable to do it.

kindly help me subtract all VBF from total diagrams to get Anihiliation diagrams.

**Comment by umar0341** [comment]
Model is general 2HDM and i updated the question

**Comment by oliviermattelaer** [comment]
So yes,

my proposal to use the 
> A | B > 
syntax seems to split the diagram in the two set that you want.
i.e.
mu+ mu- > z |  a |  h1  | h2 | h3 >  mu+ mu- h2 h2, h2 > b b~

As usual, please check that the two subset are gauge invariant.
(the check command does not complain for this process, but this is not clear to me why this is gauge invariant)

Cheers,

Olivier

**Comment by umar0341** [comment]
this following showing error :
No particle found with name :z | h1 | h2 | h3 | a |

**Comment by oliviermattelaer** [comment]
works for me (in both supported version)

'''
MG5_aMC>generate mu+ mu- > z | a | h1 | h2 | h3 > mu+ mu- h2 h2, h2 > b b~
INFO: Checking for minimal orders which gives processes.
INFO: Please specify coupling orders to bypass this step.
INFO: Trying process: mu+ mu- > z|a|h1|h2|h3 > mu+ mu- h2 h2 WEIGHTED<=8 @1
INFO: Process has 1589 diagrams
INFO: Checking for minimal orders which gives processes.
INFO: Please specify coupling orders to bypass this step.
INFO: Trying process: h2 > b b~ WEIGHTED<=2
INFO: Process has 1 diagrams
1 processes with 1590 diagrams generated in 3.588 s
Total: 1 processes with 1590 diagrams
'''

maybe you put a "|" too much?

Now I have real trouble to understand how those two sample can be gauge invariant
in particular, you do have T-channel with 4 point interaction
h1 h1 h2 h2
where both h1 are in T-channel

I would expect that the equivalent diagram where you replace the four point
by h1 h1 > h1. > h2 h2 should be gauge related. Can you explain me why this is not the case?

Cheers,

Olivier

**Comment by umar0341** [comment]
*ok fine, I also got the same 1590 diagrams but these are a mixture of VBF
as well as Annihilation diagrams. i got Only 1199 VBF diagrams with the
following commands **mu+ mu- > mu+ mu- h2 h2  $$ z a h1 h2 h3,    i got
total 2788 diagrams (VBF & Annihilation) with mu+ mu- > mu+ mu- h2 h2 , But
now i want remaining only Annihilation 1589 diagrams How can i get these. *

**Comment by oliviermattelaer** [comment]
So then you have no choice but implementing a dedicated function to filter what you call VBF from annihilation:
https://answers.launchpad.net/mg5amcnlo/+faq/3322

**Comment by oliviermattelaer** [comment]
Well,

If that syntax is not what you want, then creating a python code to select the diagram that you want is the only option.
The detail on how to do that is in the link above.

Cheers,

Olivier

On 12 Jul 2022, at 09:02, umar0341 ***@***.******@***.***>> wrote:


*ok fine, I also got the same 1590 diagrams but these are a mixture of VBF
as well as Annihilation diagrams. i got Only 1199 VBF diagrams with the
following commands **mu+ mu- > mu+ mu- h2 h2 $$ z a h1 h2 h3, i got
total 2788 diagrams (VBF & Annihilation) with mu+ mu- > mu+ mu- h2 h2 , But
now i want remaining only Annihilation 1589 diagrams How can i get these. *
