### ISSUE TITLE
Two small issues

### ISSUE THREAD

**Issue by huashengshao** [mg5amcnlo/mg5amcnlo#3]
Hi Olivier,

I put the two small issues I find in the main branch.

 - [x] xlast(i) should be x*nb_hadron in pdg2pdf.f (it tries to check with x). This is fine only when nb_hadron = 1.
 - [ ] call print_zero_amp_%i() -> call print_zero_amp%i() in iolibs/export_v4.py (may not compile).

Hua-Sheng

**Comment by oliviermattelaer** [comment]
Concerning point 1:
```
[PDF]$ grep xlast . -rin
./pdg2pdf.f:81:         if (x.eq.xlast(i) .and. xmu.eq.xmulast(i) .and.
./pdg2pdf.f:100:      if (ireuse.eq.0.and.xlast(1).ne.-99d9.and.xlast(2).ne.-99d9)then
./pdg2pdf.f:102:            xlast(i)=-99d9
./pdg2pdf.f:113:      else if(ireuse.eq.0.and.xlast(1).ne.-99d9)then
./pdg2pdf.f:116:c     xlast(1).ne.-99d9). Fill the second arrays of saved values (done
./pdg2pdf.f:121:c     xlast(i) are initialized as data statements to be equal to -99d9
./pdg2pdf.f:127:      xlast(ireuse)=x*nb_hadron
./pdg2pdf_lhapdf6.f:26:      double precision xlast(20),xmulast(20),pdflast(-7:7,20)
./pdg2pdf_lhapdf6.f:28:      save ihlast,xlast,xmulast,pdflast,imemlast,ipartlast
./pdg2pdf_lhapdf6.f:31:      data xlast/20*-99d9/
./pdg2pdf_lhapdf6.f:93:               if (x*nb_hadron.eq.xlast(ii)) then
./pdg2pdf_lhapdf6.f:151:      xlast(i_replace)=x*nb_hadron
```

so indeed one should change 
./pdg2pdf.f:81:         if (x.eq.xlast(i) .and. xmu.eq.xmulast(i) .and.
to 
./pdg2pdf.f:81:         if (x*nb_hadron.eq.xlast(i) .and. xmu.eq.xmulast(i) .and.

This is very low priority since this should not be possible to have bias due to that (but a loss of performance can occur)
https://github.com/mg5amcnlo/mg5amcnlo/commit/c6d730619a364330fec45b61c22306f93b94ab39
