### ISSUE TITLE
Questions in generating events of ee->bbmumu process

### ISSUE THREAD

**Issue by zjzhao1002** [mg5amcnlo/mg5amcnlo#76]
I am opening this issue to ask some questions in generating events of ee->bbmumu process, with NLO QCD corrections. 

The run_card.dat and param_card.dat that I used are attached. I want to constrain the bb invariant mass in a Higgs window and mumu invariant mass in a Z window, so I implement two cuts:

85 GeV<M_{mumu}<95 GeV and 110 GeV<M_{bb(g)}<140 GeV.

I did that by writing some fortran codes. You can find my codes in the dummy_fct.f.

You can find my results at the attached PDF file. I have compared them with Whizard. The cross section has good agreement with Whizard, but the distributions are not.

I generated events by the Pythia8.2 shower. The parton level plots are drawn by analysing the LHE file in the Events directory.
You can see that some events has M_{bb(g)} outside the [110,140] GeV region, but these cuts work perfectly in the LO.
Is it normal?

For the hadron level, I used Fastjet to find jets with the ee kt algorithm. I require the total jet number is 2. 

You can see that both parton level and hadron level are not consistent with Whizard at NLO, but the LO results have good agreement. What may make this difference?

[mg5input.tar.gz](https://github.com/mg5amcnlo/mg5amcnlo/files/14032774/mg5input.tar.gz)
[Presentation.pdf](https://github.com/mg5amcnlo/mg5amcnlo/files/14032773/Presentation.pdf)

**Comment by zjzhao1002** [comment]
I think these cuts does work, otherwise the cross section should be much larger (even though some events escape these cuts). 

I actually did the calculation of 
e+ e- > z h > mu+ mu- b b~ [all=QCD], 
where cross section is comparable to present result.

**Comment by oliviermattelaer** [comment]
Hi,

For the cuts, those are applied at parton-level (before shower), obviously the parton-shower (and later hadronization/detector simulation) will change the kinematic of the object (either physical object and/or reconstructed object). So you can not apply the same cut at parton-level compare to the ones that you are going to apply to the analysis level since events that does not pass the cut at parton-level will pass those at analysis level (and the opposite as well).

So at parton level (either run_card or your custom cuts) you need some loose version of the  cuts and you need to apply your real cut at your analysis level.

Cheers,

Olivier

**Comment by oliviermattelaer** [comment]
What worries me is why NLO cross-section is much smaller than the one of LO.
Especially since you are using a 4 flavor scheme right?
Do you have an understanding of it?

**Comment by zjzhao1002** [comment]
> What worries me is why NLO cross-section is much smaller than the one of LO. Especially since you are using a 4 flavor scheme right? Do you have an understanding of it?

Whizard provides a resonance-aware FKS substraction. With this method, there is an additional soft mismatch component. 
I find that it is the dominant contributions to the NLO correction. It becomes important when the width of resonance is small.
In this case, the resonance is Higgs, and the Higgs width is 10^-3 GeV in my input, so it gives a large correction to the cross section. 

When I set the Higgs width to GeV level, the NLO correction becomes small. If you are interested, the technical details of this method can be found in this paper: `https://arxiv.org/pdf/1509.09071.pdf`. 

I run Madgraph5 with the standard FKS subtraction, but get the similar result. The reasons should be the same: 
1) the soft radiated gluon plays an important role; 
2) the Higgs width is narrow.

**Comment by oliviermattelaer** [comment]
So I guess that it means that you need to use that MadSTR plugin that allows to handle resonances correctly.
But Maybe I'm wrong here. @marcozaro do know if MadSTR is the solution here?

olivier

**Comment by marcozaro** [comment]
Hi,
i think MadStr is not necessary here.
What I see is that you define the bbg invariant mass by always clustering the gluon together with the b's. This, combined with the upper cut on the variable, introduces some bias. For example, you can have events where the b, bx and gluon are all hard and separated, and while m(b,bx) is in the window, m(b,bx,g) exceeds the upper limit.

In general, I would advise to make sure the cuts you apply at event generation are always looser than those after parton shower, so that they do not introduce any bias.

The fact that you are doing QCD corrections can explain why the bb spectrum is distorted while the mumu is fine.
(btw, on your page 5, the central and right histograms look identical)

Also, when you say 
`I generated events by the Pythia8.2 shower. The parton level plots are drawn by analysing the LHE file in the Events directory.`
you mean that you run pythia on the events but do not hadronise? This should be correct. What is not correct is to plot directly the LHE events without shower.

Let me know

Best,

Marco

**Comment by zjzhao1002** [comment]
In page 5, the middle plot is the bb or bbg invariant mass, while the right plot is the recoil mass, calculated from (Ecm-p_mu1-p_mu2). They must be identical, but we find that they are not after hadronization. 

I ran the generate_events script and choose Pythia8 shower. Finally, I can find a HepMC file and a LHE file in the Events directory. I mean that the parton level plots were drawn by the LHE file and the hadron level plots were drawn by the HepMC file. Events in the HepMC file should be hadronised.

**Comment by marcozaro** [comment]
Hi 

> In page 5, the middle plot is the bb or bbg invariant mass, while the right plot is the recoil mass, calculated from (Ecm-p_mu1-p_mu2). They must be identical, but we find that they are not after hadronization.

It depends, in particular if you cluster jets and you take the inv mass of the 2 b jet it may be different from the recoil invariant mass (you can have radiation outside the jet cones)

Then, LHE events are not physical per se, and plotting the LHE file without showering for a NLO run gives wrong results.
Parton-level (Fixed-Order) results in MadGraph can be obtained by setting "fixed_order = on" after the launch command, and creating a suitable analysis with histograms etc. You can find some such examples in the FixedOrderAnalisys folder.

**Comment by oliviermattelaer** [comment]
I guess that we can close this now....
